
SESSION_ID_NUM = 0
MESSAGE_ID_NUM = 1
MESSAGE_TIMESTAMP_NUM = 2
MESSAGE_FROM_NUM = 3
MESSAGE_TEXT_NUM = 4
DIALOGUE_ACTS_NUM = 5

SESSION_ID = "session.ID"
MESSAGE_ID = "Message.ID"
MESSAGE_FROM = "Message.From"
MESSAGE_TIMESTAMP = "Message.Timestamp"
MESSAGE_TEXT = "Message.Text"
DIALOGUE_ACTS = "Dialog-Acts"

